includes:
  - ../../configs/model/mattersim-1m.yml
  - data.yml
  - ../../configs/reference/residual-ridge.yml
  - objective.yml
  - ../../configs/optimizer/adamw.yml
  - ../../configs/scheduler/reduce-on-plateau.yml
  - ../../configs/trainer/default.yml
  - trainer.yml
  - checkpoint.yml
  - logging.yml
  - evaluation.yml

variables:
  data_root: ${env:MIX_HOMO_SOL_DATA_ROOT,/net/csefiles/coc-fung-cluster/lingyu/ElectrolyteData/mix-homogeneous-sol}
  single_sol_data_root: ${env:SINGLE_SOL_DATA_ROOT,/net/csefiles/coc-fung-cluster/lingyu/ElectrolyteData/single-sol}
  results_root: ${env:ELECTROLYTE_RESULTS_ROOT,/net/csefiles/coc-fung-cluster/lingyu/ElectrolyteResults}

experiment:
  name: mix-homo-sol
  output_root: ${variables.results_root}/mix-homo-sol
  output_dir: null
