data:
  train_file: ${variables.data_root}/train_mlpmd_bulk_interface.xyz
  pair_train_file: null
  test_file: null
  energy_reference: ${variables.results_root}/mix-LHCE/references/mattersim-1m-conservative-ase-pretrained-residual-ridge-alpha1p0.json
  train_split: 0.9
  shuffle: true
  shuffle_seed: 42
  batch_size: 1
  num_workers: 4
  pin_memory: false
  max_parent_frame: null
